"""Unit tests for gcode_meta.extract_thumbnail (.3mf plate render + .gcode base64 blocks)."""
import base64
import io
import zipfile

from app.services.gcode_meta import extract_thumbnail

PNG_A = b"\x89PNG\r\n\x1a\nAAAA"
PNG_B = b"\x89PNG\r\n\x1a\nBBBB"


def _zip_3mf(entries: dict[str, bytes]) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for name, data in entries.items():
            zf.writestr(name, data)
    return buf.getvalue()


def _gcode_thumb_block(width: int, height: int, png: bytes) -> bytes:
    b64 = base64.b64encode(png)
    lines = b"\n".join(b"; " + b64[i:i + 60] for i in range(0, len(b64), 60))
    return (
        f"; thumbnail begin {width}x{height} {len(b64)}\n".encode()
        + lines
        + b"\n; thumbnail end\n"
    )


def test_3mf_prefers_plate_1_bed_render():
    data = _zip_3mf({
        "Metadata/plate_2.png": PNG_B,
        "Metadata/plate_1.png": PNG_A,
        "Metadata/thumbnail/thumbnail_400x400.png": PNG_B,
    })
    assert extract_thumbnail(data, ".gcode.3mf") == PNG_A


def test_3mf_falls_back_to_fixed_thumbnails():
    data = _zip_3mf({"Metadata/thumbnail.png": PNG_B})
    assert extract_thumbnail(data, ".3mf") == PNG_B


def test_3mf_without_images_returns_none():
    data = _zip_3mf({"Metadata/plate_1.gcode": b"G28\n"})
    assert extract_thumbnail(data, ".3mf") is None


def test_gcode_picks_largest_thumbnail():
    contents = (
        b"; generated by OrcaSlicer\n"
        + _gcode_thumb_block(16, 16, PNG_B)
        + _gcode_thumb_block(300, 300, PNG_A)
        + b"G28\nG1 X10\n"
    )
    assert extract_thumbnail(contents, ".gcode") == PNG_A


def test_gcode_without_thumbnail_returns_none():
    assert extract_thumbnail(b"G28\nG1 X10\n", ".gcode") is None


def test_garbage_does_not_raise():
    assert extract_thumbnail(b"\x00\x01\x02", ".3mf") is None
