"""Unit tests for the slicer-comment parser used to extract filament metadata
from .gcode and .3mf files. These run without any DB or network."""
from __future__ import annotations

import io
import zipfile
from pathlib import Path

import pytest

from app.services.gcode_meta import _parse_time_str, _parse_text, parse_gcode


GCODE_SAMPLE = """\
; generated by OrcaSlicer
G28
G1 X0 Y0
T0
G1 E10
T1
G1 E5
; filament_type = PLA;PETG
; filament_colour = #FF0000;#00FF00
; filament used [g] = 12.5;3.2
; estimated printing time (normal mode) = 4h 32m 15s
; total layer count = 120
; layer_height = 0.2
"""

PRUSA_SEMI_GRAMS = """\
G28
; filament_type = PLA
; filament_colour = #112233
; filament used [g] = 7.7;1.1
"""


def test_parse_text_extracts_types_and_colors():
    out = _parse_text(GCODE_SAMPLE)
    assert out["types"] == ["PLA", "PETG"]
    assert out["colors"] == ["#FF0000", "#00FF00"]
    assert out["used_g"] == [12.5, 3.2]
    assert out["estimated_minutes"] == 4 * 60 + 32  # 15s rounds to 0m
    assert out["total_layers"] == 120
    assert out["layer_height"] == 0.2


def test_parse_text_handles_legacy_semicolon_used_g():
    out = _parse_text(PRUSA_SEMI_GRAMS)
    assert out["used_g"] == [7.7, 1.1]


def test_parse_text_returns_empty_for_blank_input():
    assert _parse_text("") == {}


def test_parse_text_ignores_non_comment_lines():
    # If filament_colour appears inside a G-code line (not a `;` comment) it must not be parsed.
    sketchy = "G1 X10 ; filament_colour = #FF0000 trailing"
    out = _parse_text(sketchy)
    # The line still starts with G1, not with ';', so the pattern won't match.
    assert "colors" not in out


@pytest.mark.parametrize(
    "value,expected",
    [
        ("4h 32m 15s", 4 * 60 + 32),  # 15s rounds to 0m
        ("1d 2h", 24 * 60 + 120),
        ("90s", 2),  # 90s rounds to 2
        ("45m", 45),
        ("", None),
        ("garbage", None),
    ],
)
def test_parse_time_str(value, expected):
    assert _parse_time_str(value) == expected


def test_parse_gcode_unsupported_extension(tmp_path: Path):
    p = tmp_path / "thing.txt"
    p.write_text("; filament_type = PLA")
    assert parse_gcode(p) == {}


def test_parse_gcode_reads_real_file(tmp_path: Path):
    p = tmp_path / "thing.gcode"
    p.write_text(GCODE_SAMPLE)
    out = parse_gcode(p)
    assert out["colors"] == ["#FF0000", "#00FF00"]
    assert out["types"] == ["PLA", "PETG"]


def test_parse_gcode_handles_3mf_with_embedded_gcode(tmp_path: Path):
    # OrcaSlicer / Bambu Studio: embedded gcode at Metadata/plate_1.gcode inside a ZIP.
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("Metadata/plate_1.gcode", GCODE_SAMPLE)
        zf.writestr("3D/3dmodel.model", "<?xml version='1.0'?>")
    p = tmp_path / "model.3mf"
    p.write_bytes(buf.getvalue())
    out = parse_gcode(p)
    assert out["colors"] == ["#FF0000", "#00FF00"]
    assert out["estimated_minutes"]


def test_parse_gcode_handles_double_extension_gcode_3mf(tmp_path: Path):
    """OrcaSlicer outputs 'file.gcode.3mf' — path.suffix is only '.3mf', so the
    parser has to check the full suffix chain."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("Metadata/plate_1.gcode", GCODE_SAMPLE)
    p = tmp_path / "model.gcode.3mf"
    p.write_bytes(buf.getvalue())
    out = parse_gcode(p)
    assert out["types"] == ["PLA", "PETG"]


def test_parse_gcode_corrupt_3mf_returns_empty(tmp_path: Path):
    p = tmp_path / "broken.3mf"
    p.write_bytes(b"not a zip file at all")
    assert parse_gcode(p) == {}


def test_parse_gcode_missing_file(tmp_path: Path):
    p = tmp_path / "nope.gcode"
    # No write — file does not exist
    assert parse_gcode(p) == {}
