"""File upload + send-to-printer endpoints. Moonraker upload is mocked."""
from __future__ import annotations

import io
import zipfile
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from app.api.files import GCODES_DIR


GCODE_SAMPLE = b"""\
; generated by OrcaSlicer
G28
T0
G1 E10
T1
G1 E5
; filament_type = PLA;PETG
; filament_colour = #FF0000;#00FF00
; filament used [g] = 12.5;3.2
; estimated printing time (normal mode) = 1h 30m
"""


@pytest.fixture
def cleanup_uploads():
    """Track newly-stored files so they are removed when the test finishes.
    GCODES_DIR is shared filesystem state — must not leak between tests."""
    before = set(p.name for p in GCODES_DIR.glob("*")) if GCODES_DIR.exists() else set()
    yield
    if GCODES_DIR.exists():
        for p in GCODES_DIR.glob("*"):
            if p.name not in before:
                p.unlink(missing_ok=True)


def test_list_files_empty(client, auth_headers):
    resp = client.get("/api/files", headers=auth_headers)
    assert resp.status_code == 200
    # Could be non-empty if developer has uploads sitting in data/gcodes — the
    # API self-heals based on existing rows, not the directory contents, so
    # the test DB transaction guarantees no rows exist here.
    assert resp.json() == []


def test_upload_gcode_parses_filament_meta(client, auth_headers, cleanup_uploads):
    resp = client.post(
        "/api/files/upload",
        headers=auth_headers,
        files={"file": ("test_part.gcode", GCODE_SAMPLE, "application/octet-stream")},
    )
    assert resp.status_code == 201, resp.text
    body = resp.json()
    assert body["original_name"] == "test_part.gcode"
    assert body["size_bytes"] == len(GCODE_SAMPLE)
    meta = body["filament_meta"]
    assert meta["types"] == ["PLA", "PETG"]
    assert meta["colors"] == ["#FF0000", "#00FF00"]
    assert meta["used_g"] == [12.5, 3.2]
    assert meta["estimated_minutes"] == 90


def test_upload_rejects_disallowed_extension(client, auth_headers):
    resp = client.post(
        "/api/files/upload",
        headers=auth_headers,
        files={"file": ("readme.txt", b"hello", "text/plain")},
    )
    assert resp.status_code == 400


def test_upload_handles_double_extension_gcode_3mf(client, auth_headers, cleanup_uploads):
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("Metadata/plate_1.gcode", GCODE_SAMPLE.decode())
    resp = client.post(
        "/api/files/upload",
        headers=auth_headers,
        files={"file": ("model.gcode.3mf", buf.getvalue(), "application/octet-stream")},
    )
    assert resp.status_code == 201
    # Full suffix preserved
    body = resp.json()
    assert body["original_name"] == "model.gcode.3mf"
    assert body["stored_name"].endswith(".gcode.3mf")
    # 3mf is unzipped and parsed
    assert body["filament_meta"] is not None
    assert body["filament_meta"]["types"] == ["PLA", "PETG"]


def test_moonraker_upload_shim_stores_file_with_bearer_token(client, auth_headers, cleanup_uploads):
    resp = client.post(
        "/server/files/upload",
        headers=auth_headers,
        data={"root": "gcodes", "print": "true"},
        files={"file": ("orca_part.gcode", GCODE_SAMPLE, "application/octet-stream")},
    )
    assert resp.status_code == 201, resp.text
    body = resp.json()
    assert body["item"]["path"] == "orca_part.gcode"
    assert body["item"]["root"] == "gcodes"
    assert body["print_started"] is False
    assert body["action"] == "create_file"
    assert body["monofarm"]["file_id"] > 0
    assert body["monofarm"]["print_requested"] is True
    assert "/auth/webview" in body["url"]
    assert resp.headers["location"].endswith("/orca_part.gcode")

    files = client.get("/api/files", headers=auth_headers).json()
    assert any(f["original_name"] == "orca_part.gcode" for f in files)


def test_delete_file_removes_row_and_disk(client, auth_headers, cleanup_uploads, admin_user):
    from app.services import storage as storage_svc
    up = client.post(
        "/api/files/upload",
        headers=auth_headers,
        files={"file": ("doomed.gcode", b"G28\n", "application/octet-stream")},
    )
    file_id = up.json()["id"]
    stored_name = up.json()["stored_name"]
    assert storage_svc.exists(stored_name, admin_user.organization_id) or (GCODES_DIR / stored_name).exists()

    resp = client.delete(f"/api/files/{file_id}", headers=auth_headers)
    assert resp.status_code == 204
    assert not storage_svc.exists(stored_name, admin_user.organization_id)
    assert not (GCODES_DIR / stored_name).exists()


def test_send_file_to_moonraker_printer_calls_upload(
    client, auth_headers, cleanup_uploads, mock_external_services
):
    # Create a printer with a moonraker_url
    p = client.post(
        "/api/printers",
        headers=auth_headers,
        json={"name": "U1-01", "kind": "snapmaker_u1", "moonraker_url": "http://192.168.0.10"},
    ).json()
    f = client.post(
        "/api/files/upload",
        headers=auth_headers,
        files={"file": ("part.gcode", GCODE_SAMPLE, "application/octet-stream")},
    ).json()

    resp = client.post(
        f"/api/files/{f['id']}/send/{p['id']}",
        headers=auth_headers,
        json={"slot_map": {}},
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["ok"] is True
    mock_external_services["moonraker_upload"].assert_called_once()
    # When slot_map is identity, gcode should be sent un-rewritten — verified
    # by the second positional arg being a Path to the actual stored file.
    args, kwargs = mock_external_services["moonraker_upload"].call_args
    assert args[0] == "http://192.168.0.10"


def test_send_file_with_slot_remap_uses_temp_file(
    client, auth_headers, cleanup_uploads, mock_external_services
):
    p = client.post(
        "/api/printers",
        headers=auth_headers,
        json={"name": "U1-02", "kind": "snapmaker_u1", "moonraker_url": "http://192.168.0.11"},
    ).json()
    f = client.post(
        "/api/files/upload",
        headers=auth_headers,
        files={"file": ("swap.gcode", GCODE_SAMPLE, "application/octet-stream")},
    ).json()

    resp = client.post(
        f"/api/files/{f['id']}/send/{p['id']}",
        headers=auth_headers,
        json={"slot_map": {0: 1, 1: 0}},
    )
    assert resp.status_code == 200, resp.text
    mock_external_services["moonraker_upload"].assert_called_once()
    # When a remap is requested, the upload is called with a temp file path
    # (not the original stored_name). The temp path is unlinked after the call
    # so we can only verify it's not the original.
    args, _ = mock_external_services["moonraker_upload"].call_args
    sent_path: Path = args[1]
    assert isinstance(sent_path, Path)
    # The remap rewrote the gcode, so we verify by re-reading working bytes
    # was passed to upload_gcode (we just check it was a tempfile path,
    # not the canonical stored_name in GCODES_DIR).
    assert sent_path.parent != GCODES_DIR


def test_send_to_missing_printer_returns_404(client, auth_headers, cleanup_uploads):
    f = client.post(
        "/api/files/upload",
        headers=auth_headers,
        files={"file": ("orphan.gcode", b"G28\n", "application/octet-stream")},
    ).json()
    resp = client.post(
        f"/api/files/{f['id']}/send/99999",
        headers=auth_headers,
        json={"slot_map": {}},
    )
    assert resp.status_code == 404


def test_send_bambu_only_accepts_3mf(client, auth_headers, cleanup_uploads):
    p = client.post(
        "/api/printers",
        headers=auth_headers,
        json={
            "name": "Bambu-X1",
            "kind": "bambu",
            "bambu_dev_id": "TEST123",
            "bambu_access_code": "12345678",
        },
    ).json()
    f = client.post(
        "/api/files/upload",
        headers=auth_headers,
        files={"file": ("plainpart.gcode", GCODE_SAMPLE, "application/octet-stream")},
    ).json()
    resp = client.post(
        f"/api/files/{f['id']}/send/{p['id']}",
        headers=auth_headers,
        json={"slot_map": {}},
    )
    # Should refuse: gcode not 3mf
    assert resp.status_code == 400


def test_send_bambu_3mf_creates_queued_cloud_job(client, auth_headers, cleanup_uploads, db_session):
    from app.models.bambu_cloud_job import BambuCloudJob

    p = client.post(
        "/api/printers",
        headers=auth_headers,
        json={
            "name": "Bambu-P1S",
            "kind": "bambu",
            "bambu_dev_id": "BAMBU123",
            "bambu_access_code": "12345678",
        },
    ).json()

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("Metadata/plate_1.gcode", GCODE_SAMPLE.decode())
    f = client.post(
        "/api/files/upload",
        headers=auth_headers,
        files={"file": ("cloud_part.gcode.3mf", buf.getvalue(), "application/octet-stream")},
    ).json()

    resp = client.post(
        f"/api/files/{f['id']}/send/{p['id']}",
        headers=auth_headers,
        json={"slot_map": {"0": 0, "1": 1}},
    )

    assert resp.status_code == 202, resp.text
    body = resp.json()
    assert body["ok"] is True
    assert body["status"] == "queued"
    assert body["job_id"]

    job = db_session.get(BambuCloudJob, body["job_id"])
    assert job is not None
    assert job.printer_id == p["id"]
    assert job.gcode_file_id == f["id"]
    assert job.printer_bambu_dev_id == "BAMBU123"
    assert job.file_name == "cloud_part.gcode.3mf"
    assert job.file_size == f["size_bytes"]
    assert job.request_payload_json["ams_mapping"] == [0, 1]


def test_send_bambu_3mf_respects_cloud_feature_flag(client, auth_headers, cleanup_uploads, monkeypatch):
    from app.api import files as files_api

    p = client.post(
        "/api/printers",
        headers=auth_headers,
        json={
            "name": "Bambu-Flag",
            "kind": "bambu",
            "bambu_dev_id": "BAMBU-FLAG",
            "bambu_access_code": "12345678",
        },
    ).json()

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("Metadata/plate_1.gcode", GCODE_SAMPLE.decode())
    f = client.post(
        "/api/files/upload",
        headers=auth_headers,
        files={"file": ("flagged.3mf", buf.getvalue(), "application/octet-stream")},
    ).json()

    monkeypatch.setattr(files_api.settings, "BAMBU_CLOUD_V2_ENABLED", False)
    resp = client.post(
        f"/api/files/{f['id']}/send/{p['id']}",
        headers=auth_headers,
        json={"slot_map": {}},
    )

    assert resp.status_code == 503
    assert "disabled" in resp.json()["detail"]


def test_bambu_job_endpoints_list_active_cancel_and_retry(client, auth_headers, cleanup_uploads, db_session, monkeypatch):
    from datetime import datetime, timezone

    from app.models.bambu_cloud_job import BambuCloudJob, BambuCloudJobStatus
    from app.services import bambu_dispatch

    p = client.post(
        "/api/printers",
        headers=auth_headers,
        json={
            "name": "Bambu-A1",
            "kind": "bambu",
            "bambu_dev_id": "BAMBU-A1",
            "bambu_access_code": "12345678",
        },
    ).json()
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("Metadata/plate_1.gcode", GCODE_SAMPLE.decode())
    f = client.post(
        "/api/files/upload",
        headers=auth_headers,
        files={"file": ("queued.3mf", buf.getvalue(), "application/octet-stream")},
    ).json()
    queued = client.post(
        f"/api/files/{f['id']}/send/{p['id']}",
        headers=auth_headers,
        json={"slot_map": {}},
    ).json()
    job_id = queued["job_id"]

    active = client.get(f"/api/printers/{p['id']}/active-job", headers=auth_headers)
    assert active.status_code == 200
    assert active.json()["id"] == job_id

    listed = client.get("/api/bambu-jobs?statuses=queued", headers=auth_headers)
    assert listed.status_code == 200
    assert listed.json()["total"] == 1
    assert listed.json()["items"][0]["id"] == job_id

    cancelled = client.post(f"/api/bambu-jobs/{job_id}/cancel", headers=auth_headers)
    assert cancelled.status_code == 200
    assert cancelled.json()["status"] == "cancelled"

    cancelled_retry = client.post(f"/api/bambu-jobs/{job_id}/retry", headers=auth_headers)
    assert cancelled_retry.status_code == 409

    job = db_session.get(BambuCloudJob, job_id)
    job.status = BambuCloudJobStatus.failed
    job.status_reason = "Retryable worker failure"
    job.error_code = "DISPATCH_FAILED"
    job.error_details_json = {"retryable": True}
    job.failed_at = datetime.now(timezone.utc)
    db_session.commit()

    monkeypatch.setattr(
        bambu_dispatch,
        "dispatch_cloud_job",
        MagicMock(side_effect=AssertionError("retry endpoint must not dispatch inline")),
    )

    retried = client.post(f"/api/bambu-jobs/{job_id}/retry", headers=auth_headers)
    assert retried.status_code == 200
    assert retried.json()["ok"] is True
    assert retried.json()["job"]["status"] == "queued"
    assert retried.json()["job"]["retry_count"] == 1
