"""Built-in label templates (not stored in DB, merged at query time)."""

BUILTIN_TEMPLATES = [
    {
        "id": -7,
        "name": "Клітинка — 58×40мм (Zebra термо)",
        "item_type": "cell",
        "width_mm": 58.0,
        "height_mm": 40.0,
        "is_builtin": True,
        "is_default": False,
        "elements": [
            {"id": "qr",   "type": "qr",   "x": 2,   "y": 2,  "w": 36, "h": 36, "value": "{{CELL_QR}}", "level": "M"},
            {"id": "code", "type": "text", "x": 40,  "y": 5,  "w": 16, "h": 10, "text": "{{code}}",      "fontSize": 7.5, "fontWeight": "bold",   "color": "#111", "align": "left"},
            {"id": "zone", "type": "text", "x": 40,  "y": 17, "w": 16, "h": 7,  "text": "{{zone_name}}", "fontSize": 4.5, "fontWeight": "normal", "color": "#555", "align": "left"},
            {"id": "note", "type": "text", "x": 40,  "y": 26, "w": 16, "h": 5,  "text": "{{notes}}",     "fontSize": 3.5, "fontWeight": "normal", "color": "#999", "align": "left"},
            {"id": "div",  "type": "line", "x": 39,  "y": 2,  "w": 0.5,"h": 36, "strokeColor": "#ccc",   "strokeWidth": 0.3, "orientation": "vertical"},
        ],
    },
    {
        "id": -1,
        "name": "Клітинка — 57×32мм",
        "item_type": "cell",
        "width_mm": 57.0,
        "height_mm": 32.0,
        "is_builtin": True,
        "is_default": False,
        "elements": [
            {"id": "qr",   "type": "qr",   "x": 2,  "y": 2,  "w": 28, "h": 28, "value": "{{CELL_QR}}", "level": "M"},
            {"id": "code", "type": "text", "x": 32, "y": 5,  "w": 22, "h": 9,  "text": "{{code}}",      "fontSize": 8, "fontWeight": "bold", "color": "#111", "align": "left"},
            {"id": "zone", "type": "text", "x": 32, "y": 16, "w": 22, "h": 6,  "text": "{{zone_name}}", "fontSize": 4, "fontWeight": "normal", "color": "#555", "align": "left"},
            {"id": "note", "type": "text", "x": 32, "y": 24, "w": 22, "h": 5,  "text": "{{notes}}",     "fontSize": 3.5, "fontWeight": "normal", "color": "#999", "align": "left"},
        ],
    },
    {
        "id": -2,
        "name": "Клітинка — 50×25мм",
        "item_type": "cell",
        "width_mm": 50.0,
        "height_mm": 25.0,
        "is_builtin": True,
        "is_default": False,
        "elements": [
            {"id": "qr",   "type": "qr",   "x": 1.5, "y": 1.5, "w": 22, "h": 22, "value": "{{CELL_QR}}", "level": "M"},
            {"id": "code", "type": "text", "x": 25,  "y": 4,   "w": 23, "h": 8,  "text": "{{code}}",      "fontSize": 7, "fontWeight": "bold",   "color": "#111", "align": "left"},
            {"id": "zone", "type": "text", "x": 25,  "y": 14,  "w": 23, "h": 5,  "text": "{{zone_name}}", "fontSize": 3.5, "fontWeight": "normal", "color": "#555", "align": "left"},
        ],
    },
    {
        "id": -3,
        "name": "Товар — 100×30мм (A4)",
        "item_type": "product",
        "width_mm": 100.0,
        "height_mm": 30.0,
        "is_builtin": True,
        "is_default": False,
        "elements": [
            {"id": "img",  "type": "image",   "x": 1.5, "y": 1.5, "w": 20, "h": 27, "source": "product_image", "objectFit": "cover"},
            {"id": "name", "type": "text",    "x": 23,  "y": 3,   "w": 29, "h": 7,  "text": "{{name}}",        "fontSize": 4.5, "fontWeight": "bold",   "color": "#111", "align": "left"},
            {"id": "cats", "type": "text",    "x": 23,  "y": 12,  "w": 29, "h": 5,  "text": "{{categories}}",  "fontSize": 3.5, "fontWeight": "normal", "color": "#555", "align": "left"},
            {"id": "sku",  "type": "text",    "x": 23,  "y": 19,  "w": 29, "h": 5,  "text": "{{sku}}",         "fontSize": 3.5, "fontWeight": "normal", "color": "#999", "align": "left"},
            {"id": "bc",   "type": "barcode", "x": 54,  "y": 2,   "w": 44, "h": 26, "value": "{{PROD_QR}}",    "barcodeFormat": "CODE128", "showText": False},
        ],
    },
    {
        "id": -4,
        "name": "Товар — 57×32мм (Zebra)",
        "item_type": "product",
        "width_mm": 57.0,
        "height_mm": 32.0,
        "is_builtin": True,
        "is_default": False,
        "elements": [
            {"id": "qr",   "type": "qr",   "x": 2,  "y": 2,  "w": 28, "h": 28, "value": "{{PROD_QR}}", "level": "M"},
            {"id": "name", "type": "text", "x": 32, "y": 4,  "w": 22, "h": 8,  "text": "{{name}}",     "fontSize": 5.5, "fontWeight": "bold",   "color": "#111", "align": "left"},
            {"id": "sku",  "type": "text", "x": 32, "y": 14, "w": 22, "h": 5,  "text": "{{sku}}",      "fontSize": 3.5, "fontWeight": "normal", "color": "#555", "align": "left"},
            {"id": "cats", "type": "text", "x": 32, "y": 21, "w": 22, "h": 5,  "text": "{{categories}}","fontSize": 3.5, "fontWeight": "normal", "color": "#888", "align": "left"},
        ],
    },
    {
        "id": -5,
        "name": "Дія сканера — 100×100мм",
        "item_type": "action",
        "width_mm": 100.0,
        "height_mm": 100.0,
        "is_builtin": True,
        "is_default": False,
        "elements": [
            {"id": "qr",    "type": "qr",   "x": 18, "y": 5,  "w": 64, "h": 64, "value": "{{ACTION_QR}}", "level": "M"},
            {"id": "label", "type": "text", "x": 4,  "y": 73, "w": 92, "h": 14, "text": "{{label}}",      "fontSize": 11, "fontWeight": "bold",   "color": "#111", "align": "center"},
            {"id": "code",  "type": "text", "x": 4,  "y": 88, "w": 92, "h": 7,  "text": "{{code}}",       "fontSize": 5,  "fontWeight": "normal", "color": "#999", "align": "center"},
        ],
    },
    {
        "id": -6,
        "name": "Дія сканера — 57×32мм (Zebra)",
        "item_type": "action",
        "width_mm": 57.0,
        "height_mm": 32.0,
        "is_builtin": True,
        "is_default": False,
        "elements": [
            {"id": "qr",    "type": "qr",   "x": 2,  "y": 2,  "w": 28, "h": 28, "value": "{{ACTION_QR}}", "level": "M"},
            {"id": "label", "type": "text", "x": 32, "y": 5,  "w": 22, "h": 9,  "text": "{{label}}",      "fontSize": 6.5, "fontWeight": "bold",   "color": "#111", "align": "left"},
            {"id": "code",  "type": "text", "x": 32, "y": 16, "w": 22, "h": 5,  "text": "{{code}}",       "fontSize": 3.5, "fontWeight": "normal", "color": "#999", "align": "left"},
        ],
    },
]
